### ISSUE TITLE
w.opt undefined (cannot refer to unexported field or method opt)

### ISSUE THREAD

**Issue by paulm17** [taylorchu/work#15]
Many thanks for developing this new version of work.

*** Issue Solved ***

**Enqueuer:**

	package main

	import (
		"fmt"

		"github.com/go-redis/redis"
		"github.com/taylorchu/work"
	)

	type message struct {
		Text string
	}

	func main() {
		client := newRedisClient()
		defer client.Close()

		job := work.NewJob()
		err := job.MarshalPayload(message{Text: "hello"})

		if (err != nil) {
			panic(err)
		}

		err = work.NewRedisQueue(client).Enqueue(job, &work.EnqueueOptions{
			Namespace: "ns1",
			QueueID:   "worker",
		})

		if (err != nil) {
			panic(err)
		}

		fmt.Println("job submitted")
	}

	func newRedisClient() *redis.Client {
		return redis.NewClient(&redis.Options{
			Addr:         "127.0.0.1:6379",
			PoolSize:     10,
			MinIdleConns: 10,
		})
	}

**Worker:**

	package main

	import (
		"fmt"
		"os"
	    "os/signal"
		"time"

		"github.com/go-redis/redis"
		"github.com/taylorchu/work"
	)

	type message struct {
		Text string
	}

	func main() {
		client := newRedisClient()
		defer client.Close()

		w := work.NewWorker(&work.WorkerOptions{
			Namespace: "ns1",
			Queue:     work.NewRedisQueue(client),
		})
		err := w.Register("worker",
			func(job *work.Job, _ *work.DequeueOptions) error {
				var msg message
				job.UnmarshalPayload(&msg)
				fmt.Println(msg)
				return nil
			},
			&work.JobOptions{
				MaxExecutionTime: time.Second,
				IdleWait:         time.Second,
				NumGoroutines:    2,
			},
		)

		if (err != nil) {
			panic(err)
		}

		fmt.Println("starting")

		w.Start()

		// Wait for a signal to quit:
	    signalChan := make(chan os.Signal, 1)
	    signal.Notify(signalChan, os.Interrupt, os.Kill)
	    <-signalChan

	    fmt.Println("stopped")

	    w.Stop()
	}

	func newRedisClient() *redis.Client {
		return redis.NewClient(&redis.Options{
			Addr:         "127.0.0.1:6379",
			PoolSize:     10,
			MinIdleConns: 10,
		})
	}

**Comment by taylorchu** [comment]
`NewWorker` is for dequeuing and running the jobs only. You can use NewRedisQueue to create a queue to enqueue.

**Comment by paulm17** [comment]
Many thanks for the clarification.  I'll leave an amended version in case anyone comes across this and wants to see a working example.

**Comment by chriskolenko** [comment]
Damn it. I actually needed this 10 hours ago.
