### ISSUE TITLE
What value should be used as QueueID?

### ISSUE THREAD

**Issue by ehnuje** [taylorchu/work#20]
Dear devs, currently I'm using v1, but to use Redis Cluster, we're trying to change our package from v1 to v2. And I wonder what value should I use for QueueID.  Also, what's the purpose of QueueID?

**Comment by taylorchu** [comment]
the id can be any name allowed as redis key. for example, `welcome_message_mailer`.

**Comment by ehnuje** [comment]
@taylorchu Thanks! So the point is to use the same QueueID for `Register` and `EnqueueOptions`, right?

**Comment by taylorchu** [comment]
yes. they should be the same.
