### ISSUE TITLE
Catch Panic Middleware

### ISSUE THREAD

**Issue by nickdelja** [taylorchu/work#25]
I ended up creating middleware for catching panics similar to how you are doing it `worker.go`

I am using logger middleware and it was not getting the panic error message because it was happening outside of the middleware process.

**Comment by taylorchu** [comment]
It turns out we never open-source this part. I will add that soon.

```go
func catchPanic(f work.HandleFunc) work.HandleFunc {
	return func(job *work.Job, opt *work.DequeueOptions) (err error) {
		defer func() {
			if r := recover(); r != nil {
				const size = 4096
				stack := make([]byte, size)
				stack = stack[:runtime.Stack(stack, false)]

				err = fmt.Errorf("panic: %v\n\n%s", r, stack)
			}
		}()
		return f(job, opt)
	}
}
```
