### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by ironsalsa** [taylorchu/work#28]
I've been using Work v1 and watching this repo - has v2 been abandoned? The original repo has much more activity to date.

**Comment by taylorchu** [comment]
no :) 
This project might need more readme, but at this point, most newer features will come in middleware.

**Comment by ironsalsa** [comment]
So if we're working on a new project, would you recommend v2 over v1 at this time?

**Comment by taylorchu** [comment]
yeah, it should have less bugs, and we already migrated to use this.

**Comment by ironsalsa** [comment]
Thanks! Last question - will this be the final place for the completed code, or will it be pulled back into the old repo eventually?

**Comment by taylorchu** [comment]
It will likely stay where for a while. we have no plan to move it back yet.

**Comment by ironsalsa** [comment]
Thanks! That answers my questions.
