### ISSUE TITLE
Job's MaxExecutionTime option does not work

### ISSUE THREAD

**Issue by genert** [taylorchu/work#33]
This line does not work - https://github.com/taylorchu/work/blob/17fd835912a7e85f3350c28eb9e702dabd08bddb/cmd/worker/main.go#L58

As nothing is ever done when context deadline is exceeded. Perhaps move this logic to worker loop?

**Comment by taylorchu** [comment]
https://github.com/taylorchu/work/blob/17fd835912a7e85f3350c28eb9e702dabd08bddb/cmd/worker/main.go#L62

this will stop the command after deadline is exceeded. do you mean supporting context in handler?

**Comment by genert** [comment]
You are correct, missed that part when reading the code.

However, it is confusing because I assume that the worker will take care of the context's deadline because that is what the job option `MaxExecutionTime` implies, no? Aka the job has max execution time.

What do you think about following logic instead:
- after job has been dequeued and if job's `MaxExecutionTime` is not nil and greater than 0, then create timeout context with the option's duration value in the worker's loop
- call handle
- if context's `<-ctx.Done()` gets triggered before handle returns, then that job must be cancelled and retried with backoff

In that way, you do not have to define `context.WithTimeout` in job.

**Comment by taylorchu** [comment]
cancellation requires subfunctions to respect context timeout, and exit themselves, so we cannot do exactly what you said. but we could change the handler function signature to support it in the next major version.

**Comment by taylorchu** [comment]
done in #41
