### ISSUE TITLE
[QUESTION] Does the reaper still exist?

### ISSUE THREAD

**Issue by ping-localhost** [taylorchu/work#35]
I was wondering, does this repository still have the reaper element from gocraft/work? As in, what happens to jobs that are stuck? 

The README doesn't really explain what from v1 still exists which makes it hard to refactor my codebase (since I don't need what I have to build myself and what is already done by this repo).

**Comment by taylorchu** [comment]
In this new design, there is no separate in progress queue, so we don’t need reaper. No job will ever get stuck in inprogress.
