### ISSUE TITLE
[QUESTION] How to assign priority to job/task

### ISSUE THREAD

**Issue by ping-localhost** [taylorchu/work#37]
In https://github.com/gocraft/work/ it was possible to assign priority using 
```golang
pool.JobWithOptions("name", work.JobOptions{Priority: 10}, fn interface{})
```

Is this still possible in this new version or all jobs equal?

**Comment by taylorchu** [comment]
All jobs are equal. You can have dedicated runner for certain queues, if you worry about starvation.
