### ISSUE TITLE
ContextJobFunc and HeartbeatMiddleware incompatible?

### ISSUE THREAD

**Issue by jpalawaga** [taylorchu/work#93]
ContextJobFunc by default sets a context timeout, but this is not really compatible with long-running jobs/heartbeating.

I plan to fix this on a fork later today, but also happy to contribute a change upstream. I just need to figure out what an optimal fix would look like.

**Comment by taylorchu** [comment]
Could you explain "not really compatible with long-running jobs/heartbeating"?

The intended usage is that we set a long timeout for context timeout, and in heartbeater it will periodically extend a short lease while the job is running.

**Comment by jpalawaga** [comment]
Ah. that actually makes sense. I guess the way I was thinking about it was, either I want a deterministic maximum execution time, or I want no maximum. Picking some arbitrarily long maximum never occurred to me, but looking at the code, it is fine to use it exactly as you describe.

**Comment by jpalawaga** [comment]
thanks for taking the time to respond!

**Comment by taylorchu** [comment]
np!

**Comment by jpalawaga** [comment]
I did encounter a bug that had me revert to my branch w/ context cancelation removed: if a job dies with a long expiry, it could stay invisible for a long time if the heartbeat hasn't had a chance to fire.

This means that long-running jobs that get killed shortly into their lifespan could sit idle for quite some time.

Not really sure what the solve is. This was causing a mysterious "where did my job go? lol" phenomenon.
